# Generated by Django 4.2.11 on 2024-05-06 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_moodcheckrecordpage_moodchecksubmission_formfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_emotion_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MoodHomePage',
        ),
    ]
